spack:
  concretizer:
    unify: when_possible
  
  config:
    install_tree:
       root: $env/install
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles
        tcl: $env/install/modulefiles

  view: false
  include: []

  # Notes.
  # jedi-ewok-env does not build on macOS with GCC
  # jedi-tools-env does not build with Intel
  specs:
   - jedi-ewok-env # ^cmake@3.23.1 +ownlibs
   - jedi-fv3-env # ^cmake@3.23.1 +ownlibs
   - jedi-tools-env # ^cmake@3.23.1 +ownlibs
   - jedi-ufs-env # ^cmake@3.23.1 +ownlibs
   - jedi-um-env # ^cmake@3.23.1 +ownlibs
   - global-workflow-env # ^cmake@3.23.1 +ownlibs
   - ufs-srw-app-env # ^cmake@3.23.1 +ownlibs
   - ufs-weather-model-env # ^cmake@3.23.1 +ownlibs
   - upp-env # ^cmake@3.23.1 +ownlibs
   - ww3-env # ^cmake@3.23.1 +ownlibs
   - gsi-env # ^cmake@3.23.1 +ownlibs
   - ufs-pyenv # ^cmake@3.23.1 +ownlibs
   - ufs-utils-env # ^cmake@3.23.1 +ownlibs
   - nceplibs-env # ^cmake@3.23.1 +ownlibs
   - soca-env # ^cmake@3.23.1 +ownlibs
