packages:
  all:
    compiler:: [intel@2021.3.0]
    providers:
      mpi:: [intel-oneapi-mpi@2021.3.0]
      # Remove the next three lines to switch to intel-oneapi-mkl
      blas:: [openblas]
      fftw-api:: [fftw]
      lapack:: [openblas]
  mpi:
    buildable: False
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.3.0%intel@2021.3.0
      prefix: /apps/oneapi
      modules:
      - impi/2021.3.0
  intel-oneapi-mkl:
    # Remove buildable: False and configure+uncomment externals section below to use intel-oneapi-mkl
    buildable: False
    #externals:
    #- spec: intel-oneapi-mkl@2022.0.2%intel@2021.3.0
    #  prefix: /apps/oneapi
  # DH* Remove this section to switch to intel-oneapi-mkl
  ectrans:
    require::
    - '@1.2.0 ~mkl +fftw'
  gsibec:
    require::
    - '@1.2.1 ~mkl'
  py-numpy:
    require::
    - '@:1.25 ^openblas'
  # *DH
