# Template spack.yaml for apps
spack:
  concretization: separately
  view: false
  include:
  - site.yaml
  - config.yaml
  - packages.yaml
  - modules.yaml
  - ${SPACK_STACK_DIR}/configs/repos/repos.yaml

# File in specs
  specs:  
