compilers::
- compiler:
    spec: clang@13.0.0
    paths:
      cc: /usr/local/opt/llvm/bin/clang
      cxx: /usr/local/opt/llvm/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    flags: {}
    operating_system: monterey
    target: x86_64
    modules: []
    environment:
        prepend_path:
          PATH: '/usr/local/opt/llvm/bin'
          CPATH: '/usr/local/opt/llvm/include'
          LD_LIBRARY_PATH: '/usr/local/opt/llvm/lib'
    extra_rpaths:
    - '/usr/local/opt/llvm/lib'
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: /usr/local/bin/gcc-11
      cxx: /usr/local/bin/g++-11
      f77: /usr/local/bin/gfortran-11
      fc: /usr/local/bin/gfortran-11
    flags: {}
    operating_system: monterey
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: apple-clang@13.0.0
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    flags: {}
    operating_system: monterey
    target: any
    modules: []
    environment: {}
    extra_rpaths: []
