compilers::
  - compiler:
      spec: intel@2022.0.2
      paths:
        cc: /glade/u/apps/opt/intel/2022.1/compiler/2022.0.2/linux/bin/intel64/icc
        cxx: /glade/u/apps/opt/intel/2022.1/compiler/2022.0.2/linux/bin/intel64/icpc
        f77: /glade/u/apps/opt/intel/2022.1/compiler/2022.0.2/linux/bin/intel64/ifort
        fc: /glade/u/apps/opt/intel/2022.1/compiler/2022.0.2/linux/bin/intel64/ifort
      flags: {}
      operating_system: sles12
      target: x86_64
      modules:
      - intel/2022.1
      environment:
        prepend_path:
          PATH: '/glade/u/apps/ch/opt/gnu/10.1.0/bin'
          CPATH: '/glade/u/apps/ch/opt/gnu/10.1.0/include'
          LD_LIBRARY_PATH: '/glade/u/apps/opt/intel/2022.1/compiler/2022.0.2/linux/compiler/lib/intel64_lin:/glade/u/apps/ch/opt/gnu/10.1.0/lib64'
        set:
          I_MPI_ROOT: '/glade/u/apps/opt/intel/2022.1/mpi/2021.5.1'
      extra_rpaths: []
  - compiler:
      spec: gcc@10.1.0
      paths:
        cc: /glade/u/apps/ch/opt/gnu/10.1.0/bin/gcc
        cxx: /glade/u/apps/ch/opt/gnu/10.1.0/bin/g++
        f77: /glade/u/apps/ch/opt/gnu/10.1.0/bin/gfortran
        fc: /glade/u/apps/ch/opt/gnu/10.1.0/bin/gfortran
      flags: {}
      operating_system: sles12
      target: x86_64
      modules:
      - gnu/10.1.0
      extra_rpaths: []
