compilers::

  - compiler:
      spec: intel@2021.2.0
      paths:
        cc: /glade/u/apps/opt/intel/2021.2/compiler/latest/linux/bin/intel64/icc
        cxx: /glade/u/apps/opt/intel/2021.2/compiler/latest/linux/bin/intel64/icpc
        f77: /glade/u/apps/opt/intel/2021.2/compiler/latest/linux/bin/intel64/ifort
        fc: /glade/u/apps/opt/intel/2021.2/compiler/latest/linux/bin/intel64/ifort
      flags: {}
      operating_system: sles12
      target: x86_64
      modules:
      - intel/2021.2
      # DH*
      #environment:
      #  prepend_path:
      #    LD_LIBRARY_PATH: '/glade/u/apps/opt/intel/2021.2/compiler/2021.2.0/linux/compiler/lib/intel64_lin'
      #    CXXFLAGS: '-gxx-name=/glade/u/apps/ch/opt/gnu/10.1.0/bin/g++ -Wl,-rpath,/glade/u/apps/ch/opt/gnu/10.1.0/lib64 -lstdc++'
      #    LDFLAGS: '-gxx-name=/glade/u/apps/ch/opt/gnu/10.1.0/bin/g++ -Wl,-rpath,/glade/u/apps/ch/opt/gnu/10.1.0/lib64 -lstdc++'
      environment:
        prepend_path:
          LD_LIBRARY_PATH: '/glade/u/apps/opt/intel/2021.2/compiler/2021.2.0/linux/compiler/lib/intel64_lin:/glade/u/apps/ch/opt/gnu/10.1.0/lib64'
          #CXXFLAGS: '-std=c++14'
          CXXFLAGS: '-std=c++14 -gxx-name=/glade/u/apps/ch/opt/gnu/10.1.0/bin/g++ -Wl,-rpath,/glade/u/apps/ch/opt/gnu/10.1.0/lib64'
          #LDFLAGS: '-std=c++14 -gxx-name=/glade/u/apps/ch/opt/gnu/10.1.0/bin/g++ -Wl,-rpath,/glade/u/apps/ch/opt/gnu/10.1.0/lib64'
        set:
          I_MPI_ROOT: '/glade/u/apps/opt/intel/2021.2/mpi/latest'
      # *DH
      extra_rpaths: []

  - compiler:
      spec: intel@2020.1.217
      paths:
        cc: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries_2020.1.217/linux/bin/intel64/icc
        cxx: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries_2020.1.217/linux/bin/intel64/icpc
        f77: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries_2020.1.217/linux/bin/intel64/ifort
        fc: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries_2020.1.217/linux/bin/intel64/ifort
      flags: {}
      operating_system: sles12
      target: x86_64
      modules:
      - intel/19.1.1
      environment:
        prepend_path:
          LD_LIBRARY_PATH: '/glade/u/apps/opt/intel/2020u1/compilers_and_libraries_2020.1.217/linux/compiler/lib/intel64_lin'
          CXXFLAGS: '-gxx-name=/glade/u/apps/ch/opt/gnu/10.1.0/bin/g++ -Wl,-rpath,/glade/u/apps/ch/opt/gnu/10.1.0/lib64 -lstdc++'
          LDFLAGS: '-gxx-name=/glade/u/apps/ch/opt/gnu/10.1.0/bin/g++ -Wl,-rpath,/glade/u/apps/ch/opt/gnu/10.1.0/lib64 -lstdc++'
      extra_rpaths: []

  - compiler:
      spec: gcc@11.1.0
      paths:
        cc: /glade/u/apps/ch/opt/gnu/11.1.0/bin/gcc
        cxx: /glade/u/apps/ch/opt/gnu/11.1.0/bin/g++
        f77: /glade/u/apps/ch/opt/gnu/11.1.0/bin/gfortran
        fc: /glade/u/apps/ch/opt/gnu/11.1.0/bin/gfortran
      flags: {}
      operating_system: sles12
      target: x86_64
      modules:
      - gnu/11.1.0
      extra_rpaths: []

  - compiler:
      spec: gcc@4.8
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: sles12
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
