compilers::
  - compiler:
      spec: gcc@12.2.0
      paths:
        cc: /glade/u/apps/casper/23.10/spack/opt/spack/gcc/12.2.0/pucl/bin/gcc
        cxx: /glade/u/apps/casper/23.10/spack/opt/spack/gcc/12.2.0/pucl/bin/g++
        f77: /glade/u/apps/casper/23.10/spack/opt/spack/gcc/12.2.0/pucl/bin/gfortran
        fc: /glade/u/apps/casper/23.10/spack/opt/spack/gcc/12.2.0/pucl/bin/gfortran
      flags: {}
      operating_system: opensuse15
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
