compilers:
- compiler:
    spec: intel@2023.1.0
    paths:
      cc: /apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2023.1.0-sb753366rvywq75zeg4ml5k5c72xgj72/compiler/2023.1.0/linux/bin/icx
      cxx: /apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2023.1.0-sb753366rvywq75zeg4ml5k5c72xgj72/compiler/2023.1.0/linux/bin/icpx
      f77: /apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2023.1.0-sb753366rvywq75zeg4ml5k5c72xgj72/compiler/2023.1.0/linux/bin/ifx
      fc: /apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2023.1.0-sb753366rvywq75zeg4ml5k5c72xgj72/compiler/2023.1.0/linux/bin/ifx
    flags:
      cflags: -diag-disable=10441
      cxxflags: -diag-disable=10441
      fflags: -diag-disable=10448
    operating_system: rocky9
    target: x86_64
    modules:
    - intel-oneapi-compilers/2023.1.0
    environment:
      set:
        # https://github.com/ufs-community/ufs-weather-model/issues/2015#issuecomment-1864438186
        I_MPI_EXTRA_FILESYSTEM: 'ON'
    extra_rpaths: []

- compiler:
    spec: gcc@12.2.0
    paths:
      cc: /work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/bin/gcc
      cxx: /work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/bin/g++
      f77: /work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/bin/gfortran
      fc: /work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/bin/gfortran
    flags: {}
    operating_system: rocky9
    target: x86_64
    modules:
    - gcc/12.2.0
    environment: {}
    extra_rpaths: []
