compilers:
- compiler:
    spec: intel@2022.0.2
    paths:
      cc: /apps/intel-2022.1.2/intel-2022.1.2/compiler/2022.0.2/linux/bin/intel64/icc
      cxx: /apps/intel-2022.1.2/intel-2022.1.2/compiler/2022.0.2/linux/bin/intel64/icpc
      f77: /apps/intel-2022.1.2/intel-2022.1.2/compiler/2022.0.2/linux/bin/intel64/ifort
      fc: /apps/intel-2022.1.2/intel-2022.1.2/compiler/2022.0.2/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: x86_64
    modules:
    - intel/2022.1.2
    environment:
      prepend_path:
        PATH: '/apps/gcc-10.2.0/gcc-10.2.0/bin'
        LD_LIBRARY_PATH: '/apps/gcc-10.2.0/gcc-10.2.0/lib64:/apps/gcc-10.2.0/gcc-10.2.0/contrib/lib'
        CPATH: '/apps/gcc-10.2.0/gcc-10.2.0/include'
    extra_rpaths: []
- compiler:
    spec: intel@18.0.5
    paths:
      cc: /apps/intel-2018/intel-2018.u4/compilers_and_libraries_2018.5.274/linux/bin/intel64/icc
      cxx: /apps/intel-2018/intel-2018.u4/compilers_and_libraries_2018.5.274/linux/bin/intel64/icpc
      f77: /apps/intel-2018/intel-2018.u4/compilers_and_libraries_2018.5.274/linux/bin/intel64/ifort
      fc: /apps/intel-2018/intel-2018.u4/compilers_and_libraries_2018.5.274/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: x86_64
    modules:
    - intel/2018.4
    environment:
      prepend_path:
        PATH: '/apps/gcc-8/gcc-8.3.0/bin'
        LD_LIBRARY_PATH: '/apps/gcc-8/gcc-8.3.0/lib64:/apps/gcc-8/gcc-8.3.0//lib:/apps/gcc-8/gcc-8.3.0/mpfr-4.0.2/lib:/apps/gcc-8/gcc-8.3.0/mpc-1.1.0/lib:/apps/gcc-8/gcc-8.3.0/gmp-6.1.2/lib'
        CPATH: '/apps/gcc-8/gcc-8.3.0/include'
    extra_rpaths: []
- compiler:
    spec: gcc@10.2.0
    paths:
      cc: /apps/gcc-10.2.0/gcc-10.2.0/bin/gcc
      cxx: /apps/gcc-10.2.0/gcc-10.2.0/bin/g++
      f77: /apps/gcc-10.2.0/gcc-10.2.0/bin/gfortran
      fc: /apps/gcc-10.2.0/gcc-10.2.0/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules:
    - gcc/10.2.0
    environment: {}
    extra_rpaths: []
