mirrors:
  local-source:
    fetch:
      url: file:///work/noaa/da/role-da/spack-stack/source-cache
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///work/noaa/da/role-da/spack-stack/source-cache
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
