compilers:
- compiler:
    spec: intel@2021.6.0
    paths:
      cc: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icc
      cxx: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icpc
      f77: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/ifort
      fc: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules:
    - intel-oneapi
    - compiler/2022.1.0
    environment: 
      prepend_path:
        LD_LIBRARY_PATH: /cm/shared/apps/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin
    extra_rpaths: []
# Todo: Define gcc compiler (default for Atlantis) for Intel (ecflow)