mirrors:
  local-source:
    fetch:
      url: file:///discover/swdev/jcsda/spack-stack/source-cache
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///discover/swdev/jcsda/spack-stack/source-cache
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
