spack:
  concretization: separately
  view: false
  include:
    - site.yaml
    - config.yaml
    - packages.yaml
    - modules.yaml
    - ${SPACK_STACK_DIR}/configs/repos/repos.yaml

  specs:
    - jedi-fv3-bundle-env
    - jedi-ufs-bundle-env
    - jedi-um-bundle-env
    - jedi-tools-env
    - ufs-weather-model-env
    - nceplibs-bundle
