packages:
  all:
    compiler:: [intel@2021.6.0]
    providers:
      mpi:: [intel-oneapi-mpi@2021.6.0]
  mpi:
    buildable: False
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.5.1%intel@2021.6.0
      modules:
      - impi/2021.6.0
      prefix: /opt/spack-stack/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.4.0/intel-oneapi-mpi-2021.6.0-oeymd7y2mkbdxex2tzf7354yhwpnvhoq/mpi/2021.6.0
