compilers:
- compiler:
    spec: intel@19.1.3.304
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-intel/8.3.3
    - intel/19.1.3.304
    - craype/2.7.13
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu/8.3.3
    - gcc/12.1.0
    - craype/2.7.13
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
