compilers:
- compiler:
    spec: intel@19.1.3.304
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags:
      cflags: -static-libgcc -static-libstdc++ -Bstatic -lstdc++ -Bdynamic -lm -lpthread
      cxxflags: -static-libgcc -static-libstdc++ -Bstatic -lstdc++ -Bdynamic -lm -lpthread
      fflags: -static-libgcc -static-libstdc++ -Bstatic -lstdc++ -Bdynamic -lm -lpthread
    operating_system: sles15
    modules:
    - PrgEnv-intel/8.5.0
    - craype/2.7.17
    - intel/19.1.3.304
    - libfabric
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
- compiler:
    spec: intel@2022.0.2.262
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags:
      cflags: -static-libgcc -static-libstdc++ -Bstatic -lstdc++ -Bdynamic -lm -lpthread
      cxxflags: -static-libgcc -static-libstdc++ -Bstatic -lstdc++ -Bdynamic -lm -lpthread
      fflags: -static-libgcc -static-libstdc++ -Bstatic -lstdc++ -Bdynamic -lm -lpthread
    operating_system: sles15
    modules:
    - PrgEnv-intel/8.5.0
    - craype/2.7.17
    - intel-classic/2022.2.0.262
    - libfabric
    environment:
      prepend_path:
        PATH: /opt/cray/pe/gcc/10.2.0/bin
        LD_LIBRARY_PATH: /opt/cray/pe/gcc/10.2.0/snos/lib64
        CPATH: /opt/cray/pe/gcc/10.2.0/snos/include
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so
        # Automake-based builds are installed in lib64
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    modules:
    - PrgEnv-gnu/8.3.3
    - craype/2.7.13
    - gcc/11.2.0
    - libfabric
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
# Needed for Intel 19/2022 backend
- compiler:
    spec: gcc@10.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    modules:
    - PrgEnv-gnu/8.3.3
    - craype/2.7.13
    - gcc/10.2.0
    - libfabric
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
