spack:
  concretizer:
    unify: when_possible

  include: []

  config:
    install_tree:
      root: $env/install
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles
        tcl: $env/install/modulefiles
  packages:
    all:
      compiler: [intel]

  # jedi-tools-env does not build with Intel
  specs:
  - jedi-ewok-env
  - jedi-fv3-env
  - jedi-ufs-env
  - jedi-um-env
  - nceplibs-env
  - soca-env
