spack:
  concretization: separately
  view: false

  @CONFIG_INCLUDES@

  specs:
    - jedi-fv3-bundle-env
    - jedi-ufs-bundle-env
    - jedi-um-bundle-env
    # Do not add, this leads to duplicate packages being installed
    #- jedi-tools-env
    - soca-bundle-env
