compilers:
- compiler:
    spec: intel@=2021.5.0
    paths:
      cc: /usr/local/intel/oneapi/2021/compiler/2022.0.1/linux/bin/intel64/icc
      cxx: /usr/local/intel/oneapi/2021/compiler/2022.0.1/linux/bin/intel64/icpc
      f77: /usr/local/intel/oneapi/2021/compiler/2022.0.1/linux/bin/intel64/ifort
      fc: /usr/local/intel/oneapi/2021/compiler/2022.0.1/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles12
    target: x86_64
    modules:
    - comp/intel/2021.5.0
    environment:
      prepend_path:
        PATH: '/usr/local/other/gcc/12.1.0/bin'
        CPATH: '/usr/local/other/gcc/12.1.0/include'
        LD_LIBRARY_PATH: '/usr/local/intel/oneapi/2021/compiler/2022.0.1/linux/compiler/lib/intel64_lin:/usr/local/other/gcc/12.1.0/lib64'
      set:
        I_MPI_ROOT: '/usr/local/intel/oneapi/2021/mpi/2021.5.0'
    extra_rpaths: []
- compiler:
    spec: gcc@=12.1.0
    paths:
      cc: /usr/local/other/gcc/12.1.0/bin/gcc
      cxx: /usr/local/other/gcc/12.1.0/bin/g++
      f77: /usr/local/other/gcc/12.1.0/bin/gfortran
      fc: /usr/local/other/gcc/12.1.0/bin/gfortran
    flags: {}
    operating_system: sles12
    target: x86_64
    modules:
    - comp/gcc/12.1.0
    environment: {}
    extra_rpaths: []
