packages:
  all:
    compiler:: [oneapi@=2024.1.2]
    providers:
      mpi:: [intel-oneapi-mpi]
      blas:: [intel-oneapi-mkl]
      fftw-api:: [intel-oneapi-mkl]
      lapack:: [intel-oneapi-mkl]
  ectrans:
    require:: '+mkl ~fftw'
  gsibec:
    require:: '+mkl'
  py-numpy:
    require:
    - '^intel-oneapi-mkl'
  gmake:
    require: '@:4.2'
  mpi:
    buildable: False
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.12%oneapi@2024.1.2
      prefix: /opt/intel/oneapi
  intel-oneapi-mkl:
    externals:
    - spec: intel-oneapi-mkl@2024.1%oneapi@2024.1.2
      prefix: /opt/intel/oneapi
  intel-oneapi-runtime:
    externals:
    - spec: intel-oneapi-runtime@2024.1.2%oneapi@2024.1.2
      prefix: /opt/intel/oneapi
