# Template spack.yaml for apps
spack:
  concretization: separately
  view: false
  
  # Custom includes which can be a directory containg
  # Spack config files or a file itself.
  include: [] 

# File in specs
  specs:  
  - gldas-env
