compilers::
  - compiler:
      spec: intel@2022.0.2
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: cnl7
      target: any
      modules:
      - PrgEnv-intel
      - intel/intel-classic.2022.0.2
      environment:
        prepend_path:
          PATH: '/opt/gcc/10.3.0/snos/bin'
          CPATH: '/opt/gcc/10.3.0/snos/include'
          LD_LIBRARY_PATH: '/opt/gcc/10.3.0/snos/lib:/opt/gcc/10.3.0/snos/lib64'
        set:
          CRAYPE_LINK_TYPE: 'dynamic'
      extra_rpaths: []
