packages:
  all:
    compiler:: [intel@2021.3.0]
    providers:
      mpi:: [cray-mpich@7.7.11]

### MPI, Python, MKL
  mpi:
    buildable: False
  cray-mpich:
    externals:
    - spec: cray-mpich@7.7.11%intel@2021.3.0
      modules:
      - cray-mpich/7.7.11
  #intel-oneapi-tbb:
  #  externals:
  #  - spec: intel-oneapi-tbb@2021.3.0
  #    prefix: /opt/intel/oneapi
  #    modules:
  #    - intel/intel-classic-2021.3.0
  #intel-oneapi-mkl:
  #  externals:
  #  - spec: intel-oneapi-mkl@2021.3.0
  #    prefix: /opt/intel/oneapi
  #    modules:
  #    - intel/intel-classic-2021.3.0
  python:
    buildable: False
    externals:
    - spec: python@3.7.3+bz2+ctypes+dbm+ensurepip+lzma~nis+pyexpat+pythoncmd+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /opt/python/3.7.3.2
      modules:
      - cray-python/3.7.3.2

### All other external packages listed alphabetically
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.15.1
      prefix: /usr
  berkeley-db:
    externals:
    - spec: berkeley-db@4.8.30
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.10.2
      prefix: /usr
    # Do not use 3.20.1, build issues with eckit
    #- spec: cmake@3.20.1
    #  modules:
    #  - cmake/3.20.1
  cpio:
    externals:
    - spec: cpio@2.12
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.60.0+gssapi+ldap+nghttp2
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
  doxygen:
    externals:
    - spec: doxygen@1.8.14~graphviz~mscgen
      prefix: /usr
  # Added manually to avoid problems building udunits
  expat:
    externals:
    - spec: expat@1.6.7
      prefix: /usr
  file:
    externals:
    - spec: file@5.32
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.19.8.1
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@9.52
      prefix: /usr
  git:
    externals:
    - spec: git@2.31.1
      modules:
      - git/2.31.1
  git-lfs:
    externals:
    - spec: git-lfs@2.11.0
      modules:
      - git-lfs/2.11.0
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
  hwloc:
    externals:
    - spec: hwloc@1.11.8
      prefix: /usr
  openjdk:
    externals:
    - spec: openjdk@11.0.11_9-suse-3.56.1-x8664
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.16.3
      prefix: /usr/lib/mit
  # Added manually to avoid problems building expat and udunits
  libbsd:
    externals:
    - spec: libbsd@0.8.7
      prefix: /usr
  libfuse:
    externals:
    - spec: libfuse@2.9.7
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  lustre:
    externals:
    - spec: lustre@2.12.0.5_cray_362_g447a87c
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@6.1.20180317+termlib abi=6
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@7.9p1
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.0i-fips
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.26.1~cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
  qt:
    externals:
    - spec: qt@5.15.3
      prefix: /lustre/f2/pdata/esrl/gsd/spack-stack/qt-5.15.3
  rsync:
    externals:
    - spec: rsync@3.1.3
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@2.5.8
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.4
      prefix: /usr
  sqlite:
    externals:
    - spec: sqlite@3.36.0+fts~functions+rtree
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
  texlive:
    externals:
    - spec: texlive@20170524
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.3
      prefix: /usr
  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
