packages:
### Modification of common packages
  # Problems building shared hdf-eos2 with Intel, not needed
  hdf-eos2:
    variants: ~shared
  # Explicitly requested by GMAO collaborators
  met:
    variants: +python +grib2 +graphics +lidar2nc +modis
  # xnnpack option doesn't build on this system
  py-torch:
    variants: ~xnnpack
### All other external packages listed alphabetically
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.13.4
      prefix: /usr
  bash:
    externals:
    - spec: bash@4.3.48
      prefix: /usr/local
  berkeley-db:
    externals:
    - spec: berkeley-db@4.8.30
      prefix: /usr
  ccache:
    externals:
    - spec: ccache@3.1.9
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.11
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.3
      prefix: /usr
  file:
    externals:
    - spec: file@5.22
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.5.12
      prefix: /usr
  flex:
    # Must set buildable: false to avoid duplicate packages
    buildable: false
    externals:
    - spec: flex@2.6.4
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.1.0
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.19.2
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@9.26
      prefix: /usr
  git:
    externals:
    - spec: git@2.12.3+tcltk
      prefix: /usr
    - spec: git@2.30.2+tcltk
      prefix: /usr/local/other/git/2.30.2
      modules:
      - git/2.30.2
  git-lfs:
    externals:
    - spec: git-lfs@3.0.2
      prefix: /usr/local/other/git-lfs/3.0.2
      modules:
      - git-lfs/3.0.2
  gmake:
    externals:
    - spec: gmake@4.0
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.2
      prefix: /usr
  hwloc:
    externals:
    - spec: hwloc@1.11.5rc2-git
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.12.5
      prefix: /usr/lib/mit
  libfuse:
    externals:
    - spec: libfuse@2.9.3
      prefix: /usr
  libxpm:
    externals:
    - spec: libxpm@4.11.0
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.16
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@5.9.20140201+termlib abi=6
      prefix: /usr
  # Old re2c on Discover unable to build newer versions of ninja
  ninja:
    version:: ['1.10.2']
  perl:
    externals:
    - spec: perl@5.18.2~cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.28
      prefix: /usr
  qt:
    buildable: False
    externals:
    - spec: qt@5.15.2
      prefix: /discover/swdev/jcsda/spack-stack/qt-5.15.2/5.15.2/gcc_64
  rsync:
    externals:
    - spec: rsync@3.1.0
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@2.1.9
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.2.2
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@4.13
      prefix: /usr
  texlive:
    externals:
    - spec: texlive@20130530
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.20.3
      prefix: /usr/local/other/wget/1.20.3
      modules:
      - wget/1.20.3
  xz:
    externals:
    - spec: xz@5.0.5
      prefix: /usr
  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
