spack:
  packages:
    jpeg:
      version: [9.1.0]
    zlib:
      version: [1.2.11]
    szip:
      version: [2.1.1]
    jasper:
      version: [2.0.25]
    udunits:
      version: [2.2.28]
    hdf5:
      version: [1.10.6]
    netcdf-c:
      version: [4.7.4]
    netcdf-fortran:
      version: [4.5.3]
    netcdf-cxx4:
      version: [4.3.1]
    nco:
      version: [5.0.6]
    cdo:
      version: [1.9.8]
    parallelio:
      version: [2.5.3]
    esmf:
      version: [8.0.1]
    fms:
      version: [2021.03]
    bacio:
      version: [2.4.1]
    sigio:
      version: [2.3.2]
    sfcio:
      version: [1.4.1]
    gfsio:
      version: [1.4.1]
    w3nco:
      version: [2.4.1]
    sp:
      version: [2.3.3]
    ip:
      version: [3.3.3]
    ip2:
      version: [1.1.2]
    landsfcutil:
      version: [2.4.1]
    nemsio:
      version: [2.5.2]
    nemsiogfs:
      version: [2.5.3]
    w3emc:
      version: [2.9.2]
    g2:
      version: [3.4.5]
    g2tmpl:
      version: [1.9.1]
    crtm:
      version: [2.3.0]
    upp:
      version: [8.1.0]
    wrf-io:
      version: [1.2.0]
    bufr:
      version: [11.4.0]
    wgrib2:
      version: [2.0.7]
    prod_util:
      version: [1.2.2]
    grib-util:
      version: [1.2.3]
    ncio:
      version: [1.0.0]
    ecbuild:
      version: [3.6.1]
    eckit:
      version: [1.16.0]
    fckit:
      version: [0.9.2]
    madis:
      version: [4.3.0]
    gftl-shared:
      version: [1.3.0]
    yafyaml:
      version: [0.5.1]
    mapl:
      version: [2.7.3]

  specs: []


    
    