  compilers:
  - compiler:
      spec: intel@19.1.3.304
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - envvar/1.0
      - PrgEnv-intel/8.1.0
      - craype/2.7.10
      - intel/19.1.3.304
      environment: {}
      extra_rpaths: []
