# Concretize various environments with different compilers, mpi, and OS.
name: concretize-test

on:
  pull_request:
  push:
  workflow_dispatch:

# Use custom shell with -l so .bash_profile is sourced
defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  macos_clang_concretize:
    strategy:
      matrix:
        compiler: [clang, apple-clang]
        template: [jedi-ufs-all]
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install-env
        uses: ./.github/actions/setup-spack-stack
        with:
          templates: ${{ matrix.template }}
          compiler: ${{ matrix.compiler }}
          mpi: openmpi
          path: ${{ github.workspace }}
          concretize_only: 'true'
          site: macos.default

  macos_gcc_concretize:
    strategy:
      matrix:
        compiler: [gcc@9.4.0, gcc@10.3.0]
        template: [jedi-ufs-all]
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install-env
        uses: ./.github/actions/setup-spack-stack
        with:
          templates: ${{ matrix.template }}
          compiler: ${{ matrix.compiler }}
          mpi: openmpi
          path: ${{ github.workspace }}
          concretize_only: 'true'

  linux_gcc_concretize:
    strategy:
      matrix:
        compiler: [gcc@9.4.0, gcc@10.3.0]
        template: [jedi-ufs-all]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install-env
        uses: ./.github/actions/setup-spack-stack
        with:
          templates: ${{ matrix.template }}
          compiler: ${{ matrix.compiler }}
          mpi: openmpi
          path: ${{ github.workspace }}
          concretize_only: 'true'
          site: linux.default

  linux_intel_concretize:
    strategy:
      matrix:
        template: [jedi-ufs-all]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install-env
        uses: ./.github/actions/setup-spack-stack
        with:
          templates: ${{ matrix.template }}
          compiler: intel
          mpi: intel-oneapi-mpi
          path: ${{ github.workspace }}
          concretize_only: 'true'
          site: linux.default
